language: node_js
sudo: required
services:
  - docker

before-install:
  - docker build -t -f stannidi/docker-react -f Dockerfile.dev

script:
  - docker run stannidi/docker-react npm run test -- --coverage
